HOST = "127.0.0.1"
PORT = 50007

DT = 0.1  # 100 ms

TRAIN_LENGTH_M = 60.0
AW0_MASS_KG = 220000.0     # empty train mass (AW0) ~220 t
AW2_MASS_KG = 291600.0     # enormal passengr load (AW2) ~291.6 t
AW3_MASS_KG = 331960.0     # crush load (AW3) ~331.96 t
TRAIN_MASS_KG = AW2_MASS_KG

MAX_AXLE_LOAD_T = 15.0
AXLE_COUNT = 12
MAX_AXLE_LOAD_KG = MAX_AXLE_LOAD_T * 1000.0

MAX_SPEED_KMH = 80.0
MAX_TUNNEL_SPEED_KMH = 80.0

A_MAX = 1.2        # m/s^2 traction capability at low speed
A_BRAKE = 1.12     # m/s^2 tuned service brake capability for 100->0 km/h stop performance
A_EMERGENCY = 1.25  # m/s^2 tuned emergency brake capability while keeping service/emergency separation
MAX_JERK_MS3 = 0.75  # maximum longitudinal jerk for passenger comfort
ROTATING_MASS_FACTOR = 1.06  # equivalent mass allowance for wheels, motors and gear inertia

# Speed-dependent train running resistance, expressed as acceleration terms:
# a_resist = A + B*v + C*v^2. Grade resistance is handled separately by track gradient.
RUNNING_RESIST_A_MS2 = 0.012
RUNNING_RESIST_B_S1 = 0.00035
RUNNING_RESIST_C_INV_M = 0.00002

# Forces (N). Derived from nominal accel and nominal operating mass.
TRACTION_FORCE_N = TRAIN_MASS_KG * A_MAX
BRAKE_FORCE_N = TRAIN_MASS_KG * A_BRAKE
EMERGENCY_FORCE_N = TRAIN_MASS_KG * A_EMERGENCY

SAFETY_MARGIN_M = 60.0
OVERLAP_M = 50.0

# Brake build-up time (s)
BRAKE_BUILDUP_S = 1.5

# ATP/ATO/CBTC fixed supervision parameters.
G = 9.81

POS_UNCERT_M = 4.0
BALISE_POS_UNCERT_M = 0.8
STATION_POS_UNCERT_M = 0.5
PRECISE_STOP_POS_UNCERT_M = 0.2

ATP_P_REACTION_S = 2.5
ATP_W_REACTION_S = 0.8
ATP_SBI_REACTION_S = 1.2
ATP_EBI_REACTION_S = 1.6
ATP_INDICATION_DELAY_S = 0.8
ATP_MA_EXTRAPOLATION_S = 1.5
ATP_POS_REPORT_LATENCY_S = 0.6
ATP_ADHESION_FACTOR = 0.82
ATP_SERVICE_BRAKE_FACTOR = 1.03
ATP_EMERGENCY_BRAKE_FACTOR = 1.05
ATP_BRAKE_BUILDUP_S = max(1.2, BRAKE_BUILDUP_S - 0.2)
ATP_MIN_DECEL_MS2 = 0.15

W_TIME_S = 1.0
SBI_TIME_S = 1.5
EBI_TIME_S = 2.0
P_TIME_S = 2.0

W_SPEED_TOL_KMH = 1.0
SBI_SPEED_TOL_KMH = 2.0
EBD_SPEED_TOL_KMH = 3.0
EBI_SPEED_MARGIN_KMH = 0.5
STOP_EBI_SUPERVISION_FLOOR_KMH = 0.5
SBI_VIOLATION_EPS_KMH = 0.03

HIGH_SPEED_CURVE_BLEND_FROM_KMH = 45.0
HIGH_SPEED_CURVE_BLEND_TO_KMH = 100.0
HIGH_SPEED_TIME_MARGIN_GAIN = 0.35
HIGH_SPEED_SPEED_TOL_GAIN_KMH = 3.0
TARGET_CURVE_RESERVE_LOW_M = 20.0
TARGET_CURVE_RESERVE_HIGH_M = 140.0
ATO_TARGET_PREP_MAX_M = 280.0
ATP_TARGET_INTERVENTION_MIN_M = 400.0
STOP_TARGET_MIN_ACTIVATION_M = 280.0
STOP_TARGET_BUFFER_M = 80.0
STOP_SVL_OFFSET_M = 1.0
ROLLBACK_PROTECT_M = 1.0
CURVE_EPS_KMH = 0.5

CURVE_DISPLAY_DROP_RATE_KMH_S = {
    "P": 12.0,
    "I": 12.0,
    "W": 14.0,
    "OFF": 14.0,
    "SBI": 16.0,
    "SBD": 16.0,
    "EBI": 20.0,
    "EBD": 20.0,
}
CURVE_DISPLAY_RISE_RATE_KMH_S = {
    "P": 18.0,
    "I": 18.0,
    "W": 20.0,
    "OFF": 20.0,
    "SBI": 24.0,
    "SBD": 24.0,
    "EBI": 28.0,
    "EBD": 28.0,
}

ATO_TRACKING_MARGIN_LOW_KMH = 0.3
ATO_TRACKING_MARGIN_HIGH_KMH = 6.0
ATO_TRACKING_MARGIN_BLEND_FROM_KMH = 35.0
ATO_TRACKING_MARGIN_BLEND_TO_KMH = 100.0
LOW_SPEED_FLEX_FULL_KMH = 15.0
LOW_SPEED_FLEX_NONE_KMH = 45.0
ATO_TRACKING_MARGIN_LOW_SPEED_RELIEF_KMH = 0.05
ATO_TRACKING_MARGIN_MIN_LOW_KMH = 0.25
I_CURVE_MARGIN_LOW_KMH = 2.0
I_CURVE_MARGIN_HIGH_KMH = 12.0
ATO_EBI_GUARD_LOW_KMH = 3.5
ATO_EBI_GUARD_HIGH_KMH = 10.0

STOP_TARGET_OFFSET_M = 0.75
STOP_ACCURACY_TOL_M = 0.3
DOCKING_ZONE_M = 12.0
DOCKING_SPEED_KMH = 4.0
FINAL_CREEP_ZONE_M = 2.0
FINAL_CREEP_MIN_SPEED_KMH = 1.8
ATO_TARGET_DROP_RATE_KMH_S = 8.0
FINAL_APPROACH_MAX_SPEED_KMH = 5.0
FINAL_APPROACH_MIN_SPEED_KMH = 2.5
FINAL_APPROACH_SBI_FLOOR_KMH = 3.5
PRECISE_STOP_EBI_FLOOR_KMH = 3.0
PRECISE_STOP_SERVICE_BAND_M = 2.0
PRECISE_STOP_SBI_ENTRY_KMH = 2.8
PRECISE_STOP_EBI_GAP_KMH = 2.0

SPEED_ESTIMATION_RES_KMH = 1.0
ATO_CONTROL_RES_KMH = 0.5
VITAL_SPEED_MARGIN_KMH = 0.5

RELEASE_ZONE_M = 100.0
RELEASE_SPEED_KMH = 18.0
RELEASE_SCAN_FAST_KMH = 10.0
RELEASE_SCAN_FINE_KMH = 6.0
RELEASE_BLEND_EXP = 1.35
RELEASE_HANDOVER_START_M = 16.0
FINAL_STOP_BRAKE_ZONE_M = 8.0
RELEASE_ENTRY_MARGIN_KMH = 1.5
RELEASE_I_MARGIN_KMH = 0.35

STOP_BEACON_OFFSET_M = 25.0
JOG_MAX_DIST_M = 15.0
JOG_SPEED_KMH = 5.0
JOG_PROFILE_ACCEL_MS2 = 1.0
MANUAL_JOG_WINDOW_M = 2.0
AUTO_DOCKING_JOG_WINDOW_M = 3.0
JOG_WINDOW_EPS_M = 0.05
JOG_STATE_IDLE = "IDLE"
JOG_STATE_REQUESTED = "REQUESTED"
JOG_STATE_ACTIVE = "ACTIVE"
JOG_STATE_COMPLETED = "COMPLETED"
JOG_STATE_FAILED_LOCKED = "FAILED_LOCKED"
LOW_SPEED_ATP_GUARD_KMH = 2.0
CREEP_MAX_SPEED_KMH = 25.0
CREEP_RELEASE_CAP_KMH = 25.0

STANDSTILL_DRIFT_M = 2.0
STANDSTILL_SPEED_EPS = 0.05
COAST_BASE_DECEL = 0.12
COAST_SPEED_GAIN = 0.03
DOWNHILL_P_BUFFER_KMH_PER_GRAD = 40.0
SBI_RELEASE_HYST_KMH = 1.0

BALISE_SPACING_M = 200.0
BALISE_ERROR_MAX_M = BALISE_POS_UNCERT_M
STATION_BALISE_ZONE_M = 120.0
STATION_BALISE_SPACING_M = 25.0
STATION_BALISE_ERROR_MAX_M = 0.35
BEACON_LOCK_RELEASE_MARGIN_M = 35.0
ODOMETER_ERROR_RATE = 0.05

DCS_DELAY_MIN_S = 0.05
DCS_DELAY_MAX_S = 0.35
DCS_TIMEOUT_S = 1.0
DCS_STARTUP_GRACE_S = 1.0
SPEED_FILTER_TAU_S = 0.35

ATO_PID_KP_LOW = 0.85
ATO_PID_KP_HIGH = 0.55
ATO_PID_KI_LOW = 0.08
ATO_PID_KI_HIGH = 0.03
ATO_PID_KD_LOW = 0.10
ATO_PID_KD_HIGH = 0.04
ATO_PID_BLEND_FROM_KMH = 10.0
ATO_PID_BLEND_TO_KMH = 65.0
ATO_PID_INT_LIMIT_MS = 8.0 / 3.6

# Runtime dynamics mode. When enabled, Train.step resolves acceleration through
# physics.longitudinal_force_balance and records force telemetry. The legacy
# acceleration path remains available as a fallback.
USE_FORCE_BALANCE_RUNTIME = True

LOG_EVERY_S = 1.0

# Fixed operational layout/runtime parameters.
SOURCE_TRAIN_SPACING_M = 120.0
SOURCE_TRAIN_LENGTH_M = 200.0
SOURCE_TRAIN_START_M = -SOURCE_TRAIN_LENGTH_M
SOURCE_TRAIN_EXIT_M = 0.0
SOURCE_TRAIN_STAGING_CLEARANCE_M = 35.0
SOURCE_VISIBLE_ACTIVE_TRAINS = 2

MIN_PASSENGER_DWELL_S = 25.0

PARALLEL_ROMAN_LABELS = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]
PARALLEL_RELEASE_MARGIN_M = 5.0
DEPARTURE_RELEASE_MIN_AUTHORITY_M = 30.0
STATION_ROUTE_APPROACH_M = 800.0
TURNOUT_LOCK_S = 5.0
SOURCE_RELEASE_LOCK_S = 5.0
LINE_CENTER_SPACING_M = 4.0

